-- This module is the root of the UnlikelyIntersectionsCanonicalLaneLean Lean proof package.
import UnlikelyIntersectionsCanonicalLaneLean.Basic
import UnlikelyIntersectionsCanonicalLaneLean.SourcePackage
import UnlikelyIntersectionsCanonicalLaneLean.SourceDependencies
import UnlikelyIntersectionsCanonicalLaneLean.Formalization
import UnlikelyIntersectionsCanonicalLaneLean.ReviewerBridge
import UnlikelyIntersectionsCanonicalLaneLean.TheoremStatement
import UnlikelyIntersectionsCanonicalLaneLean.MathlibObjects
import UnlikelyIntersectionsCanonicalLaneLean.AdmissibleClass
import UnlikelyIntersectionsCanonicalLaneLean.Projection
import UnlikelyIntersectionsCanonicalLaneLean.BridgeLemmas
import UnlikelyIntersectionsCanonicalLaneLean.GateLemmas
import UnlikelyIntersectionsCanonicalLaneLean.FinalTheorem
import UnlikelyIntersectionsCanonicalLaneLean.MathlibStatement
